#!/usr/bin/python

# From: https://github.com/swaywm/sway/blob/master/contrib/inactive-windows-transparency.py

# This script requires i3ipc-python package (install it from a system package manager
# or pip).
# It makes inactive windows transparent. Use `transparency_val` variable to control
# transparency strength in range of 0…1 or use the command line argument -o.

import argparse
import i3ipc
import signal
import sys
from functools import partial

# Apps that should have transparency even when focused
focused_transparent = [
	"Discord",
	"Electron Fiddle",
	"Geary",
	"gedit",
	"Mattermost",
	"Messenger",
	"Microsoft Teams",
	"Nautilus",
	"Skype",
	"Spotify",
	"Sublime Merge",
	"Sublime Text",
	"System Monitor",
	"Tweaks",
	"Visual Studio Code"
]

def focused_opacity(name, special_opacity):
    for app in focused_transparent:
        if app in name:
            return special_opacity
    return "1"

def on_window_focus(inactive_opacity, special_opacity, ipc, event):
    global prev_focused

    focused = event.container
    workspace = ipc.get_tree().find_focused().workspace().num

    if focused.id != prev_focused.id:  # https://github.com/swaywm/sway/issues/2859
        focused.command("opacity " + focused_opacity(focused.name, special_opacity))
        prev_focused.command("opacity " + inactive_opacity)
        prev_focused = focused


def remove_opacity(ipc):
    for workspace in ipc.get_tree().workspaces():
        for w in workspace:
            w.command("opacity 1")
    ipc.main_quit()
    sys.exit(0)


if __name__ == "__main__":
    transparency_val = "0.80"

    parser = argparse.ArgumentParser(
        description="This script allows you to set the transparency of unfocused windows in sway."
    )
    parser.add_argument(
        "--opacity",
        "-o",
        type=str,
        default=transparency_val,
        help="set opacity value in range 0...1",
    )
    parser.add_argument(
        "--specialopacity",
        "-s",
        type=str,
        default="0.95",
        help="set special opacity value in range 0...1",
    )

    args = parser.parse_args()

    ipc = i3ipc.Connection()
    prev_focused = None

    for window in ipc.get_tree():
        if window.focused:
            prev_focused = window
        else:
            window.command("opacity " + args.opacity)
    for sig in [signal.SIGINT, signal.SIGTERM]:
        signal.signal(sig, lambda signal, frame: remove_opacity(ipc))
    ipc.on("window::focus", partial(on_window_focus, args.opacity, args.specialopacity))
    ipc.main()
