#!/usr/bin/python
import argparse
import gi
gi.require_version("Gio", "2.0")
from gi.repository import Gio

separater = ":-"

def get_executables(search_term):
    search_term = search_term.split(separater)[0].strip()
    print(*map(lambda app: app.get_executable(), filter(lambda app: app.get_name() == search_term, Gio.AppInfo.get_all())))

def list_apps():
    print(*map(lambda app: "{} {} {}".format(app.get_name(), separater, app.get_description()), filter(lambda app : app.should_show(), Gio.AppInfo.get_all())), sep="\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="This script allows you to set the transparency of unfocused windows in sway."
    )

    parser.add_argument(
        "--launch",
        "-l",
        type=str,
        default=None,
        help="set opacity value in range 0...1",
    )

    args = parser.parse_args()

    if args.launch:
        get_executables(args.launch)
    else:
        list_apps()
