#!/usr/bin/env sh

if [ "$#" -gt 1 ]; then
  shift
  ~/.local/bin/whatsplaying $@
else
  ~/.local/bin/whatsplaying
fi

if [[ $? != 0 ]]; then
  echo ''
fi

timing=0
while [[ $timing -le 30 ]]; do
  sleep 1
  ((timing+=1))
done

